---
# some created directories may be redundant, but are kept in case anything else
# changes, and to enable the picking and choosing of components/roles.
- name: create consul configuration directory
  sudo: yes
  file:
    path: /etc/consul
    state: directory
    mode: 0770
  tags:
    - consul
    - distributive
    - nginx

- name: create symlink to distributive nginx checklist
  sudo: yes
  file:
    state: link
    src: /usr/share/distributive/nginx.json
    dest: /etc/distributive.d/nginx.json
  tags:
    - consul
    - distributive
    - nginx

- name: register distributive tests with consul
  sudo: yes
  copy:
    src: distributive-nginx-check.json
    dest: /etc/consul/
  notify:
    - reload consul
  tags:
    - consul
    - distributive
    - nginx
