---
- name: install haproxy pkgs
  sudo: yes
  apt: "pkg=haproxy state=present update_cache=yes cache_valid_time=3600"
  tags:
    - haproxy
    - bootstrap

- name: install haproxy pkgs
  sudo: yes
  shell: "/opt/marathon-{{ marathon_version }}/bin/haproxy-marathon-bridge install_haproxy_system localhost:8080"
  notify: restart haproxy
  tags:
    - haproxy

- name: enable haproxy
  sudo: yes
  service:
    name: haproxy
    enabled: yes
    state: started
  tags:
    - haproxy

- name: setup consul service check haproxy
  sudo: yes
  copy:
    src: haproxy_service.json
    dest: /etc/consul.d/haproxy_service.json
  notify: reload consul config
  tags:
    - haproxy
