---
- name: ensure job docker images are present
  sudo: yes
  command: /usr/bin/docker pull {{ item }}
  with_items:
    - "{{ mesos_consul_image }}:{{ mesos_consul_image_tag }}"
    - "{{ marathon_consul_image }}:{{ marathon_consul_image_tag }}"
  tags:
    - marathon
    - bootstrap

- name: create json files for jobs
  sudo: yes
  template:
    src: '{{ item }}.json.j2'
    dest: /etc/marathon/{{ item }}.json
  with_items:
    - mesos-consul
    - marathon-consul
  tags:
    - marathon

- name: start jobs
  run_once: true
  sudo: yes
  command: 'curl -X PUT -d@/etc/marathon/{{ item }}.json -H "Content-Type: application/json" http://localhost:18080/v2/apps/{{ item }}'
  changed_when: false
  with_items:
    - mesos-consul
    - marathon-consul
  tags:
    - marathon

- name: set event hooks
  run_once: true
  command: 'curl -s -X POST -H "Content-Type: application/json" http://localhost:18080/v2/eventSubscriptions?callbackUrl={{ item }}'
  register: event_hook
  changed_when: false
  failed_when: "item not in event_hook.stdout"
  with_items:
    - http://marathon-consul.service.{{ consul_dns_domain }}:4000/events