---
- name: ensure customized bin
  sudo: yes
  file:
    path: /opt/bin
    state: directory
  tags:
    - consul

# Setup consul
- name: setup consul binary
  sudo: yes
  copy:
    src: consul 
    dest: /opt/bin/consul
    mode: 0755
  notify: restart consul
  tags:
    - consul

- name: ensure consul data dir
  sudo: yes
  file: 
    path: /data/consul 
    state: directory
  tags:
    - consul

- name: ensure consul config dir
  sudo: yes
  file: 
    path: /etc/consul.d 
    state: directory
  tags:
    - consul

- name: setup system service check script
  sudo: yes
  copy:
    src: system_service_check.sh
    dest: /opt/bin/system_service_check.sh
    mode: 0755
  notify: restart consul
  tags:
    - consul

- name: setup supervisor service check script
  sudo: yes
  template:
    src: supervisor_service_check.sh.j2
    dest: /opt/bin/supervisor_service_check.sh
    mode: 0755
  notify: restart consul
  tags:
    - consul

- name: setup start_consul script
  sudo: yes
  template:
    src: start_consul.sh.j2
    dest: /opt/bin/start_consul.sh
    mode: 0755
  notify: restart consul
  tags:
    - consul

- name: setup consul supervisord config
  sudo: yes
  template:
    src: consul_supervisord.conf.j2
    dest: "{{ supervisord_conf_dir }}/consul.conf"
  notify: restart consul
  tags:
    - consul

- name: start consul supervisord
  sudo: yes
  supervisorctl: 
    name: consul
    state: present
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
  tags:
    - consul
