---
- name: install collectd packages
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - collectd
    - collectd-utils
  tags:
    - collectd
    - bootstrap

- name: create collectd plugin directory
  sudo: yes
  file:
    path: /usr/share/collectd/plugins
    state: directory
    mode: 0755
  tags:
  - collectd

- name: configure collectd
  sudo: yes
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
  notify:
    - restart collectd
  tags:
    - collectd

- name: enable collectd
  sudo: yes
  service:
    name: collectd
    enabled: yes
    state: started
  tags:
    - collectd
