#!/usr/bin/env python

""" Script for setting up cluster.

Expected output:
    aws.tf for terraform
    cluster.yml for ansible extra vars
    cluster_playbook.yml for ansible playbook
"""


def load_conf():
    pass


def generate_cluster_vars():
    """ Generate vars for cluster setup.
    """
    pass
