#!/usr/bin/env sh

TEMP_DIR=/tmp/flocker

rm -rf $TEMP_DIR
mkdir -p $TEMP_DIR

bin/flocker-ca initialize $1
bin/flocker-ca create-api-certificate -o $TEMP_DIR plugin

mkdir -p ssl/certs
mkdir -p ssl/private

mv cluster.crt ssl/certs/flocker-cluster.crt
mv cluster.key ssl/private/flocker-cluster.key

mv $TEMP_DIR/plugin.crt ssl/certs/flocker-plugin.crt
mv $TEMP_DIR/plugin.key ssl/private/flocker-plugin.key
