---
- hosts: all
  vars:
    consul_servers_group: role=control
    consul_dns_domain: consul
    consul_dc: vagrant
    consul_acl_datacenter: vagrant
    consul_bootstrap_expect: 1
    mesos_cluster: vagrant
    mesos_mode: mixed
    provider: vagrant
  pre_tasks:
    - name: set vagrant ip addresses in inventory
      set_fact:
        private_ipv4: "{{ vagrant_private_ipv4 }}"
        public_ipv4: "{{ vagrant_private_ipv4 }}"
  roles:
    - common
    - collectd
    - logrotate
    - consul-template
    - docker
    - dnsmasq
    - nginx
    - consul
    - logstash
    - vault
    - zookeeper
    - mesos
    - marathon
    - chronos
    - mantlui
