---
- name: restart docker
  sudo: yes
  service:
    name: docker
    state: restarted

- name: restart etcd proxy
  sudo: yes
  supervisorctl: 
    name: etcd_proxy
    state: restarted
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
