---
- name: reload chronos
  sudo: yes
  command: systemctl daemon-reload

- name: restart chronos
  sudo: yes
  command: systemctl restart chronos

- name: reload consul
  sudo: yes
  command: "{{ consul_bin }} reload"

- name: restart nginx-chronos
  sudo: yes
  command: systemctl restart nginx-chronos

- name: reload nginx-chronos
  sudo: yes
  command: systemctl daemon-reload
