---
- name: restart etcd
  sudo: yes
  supervisorctl: 
    name: etcd
    state: restarted
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"

- include: etcd_browser.yml

- include: consul.yml
