---
- name: configure leader defaults
  sudo: yes
  template:
    src: master-defaults.j2
    dest: /etc/default/mesos-master
  notify:
    - restart mesos leader
  tags:
    - mesos

- name: write leader credentials
  sudo: yes
  when: do_mesos_framework_auth|bool or do_mesos_follower_auth|bool
  template:
    src: master-credentials.j2
    dest: /etc/mesos/credentials
    mode: 0600
  notify:
    - restart mesos leader
  tags:
    - mesos

- name: delete leader credentials
  sudo: yes
  when: not do_mesos_framework_auth|bool and not do_mesos_follower_auth|bool
  file:
    dest: /etc/mesos/credentials
    state: absent
  tags:
    - mesos

- name: wait for zookeeper to listen
  command: "/usr/local/bin/zookeeper-wait-for-listen.sh {{ inventory_hostname }}"

- name: create zookeeper acl
  sudo: yes
  command: "{{ mesos_zk_acl_cmd }}"
  notify:
    - restart mesos leader
  when: zk_mesos_user_secret is defined
  run_once: true
  tags:
    - mesos

- name: deploy iptables configuration
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: mesos-leader-consul.cfg
      dest: /etc/consul-template/config.d
  notify:
    - reload consul-template
  tags:
    - mesos

- name: deploy iptables template
  sudo: yes
  template:
    src: mesos-leader-iptables.tmpl.j2
    dest: /etc/consul-template/templates/mesos-leader-iptables.tmpl
  notify:
    reload consul-template
  tags:
    - mesos

- name: install collectd mesos-master plugin
  sudo: yes
  copy:
    src: mesos-master.py
    dest: /usr/share/collectd/plugins
    mode: u=r
  tags:
    - mesos
    - collectd

- name: configure collectd mesos-master plugin
  sudo: yes
  template:
    src: mesos-master.conf.j2
    dest: /etc/collectd.d/mesos-master.conf
  notify:
    - restart collectd
  tags:
    - mesos
    - collectd

- include: nginx-proxy.yml
