---
- name: check mesos installation
  sudo: yes
  stat: path="/usr/lib/libmesos.so"
  register: check_mesos_path
  tags:
    - mesos

- name: Download mesos
  sudo: yes
  get_url: url="https://s3.amazonaws.com/bigdata-thirdparty/mesos_cluster/mesos_{{ mesos_version }}/mesos-{{ mesos_version }}.deb" dest="/tmp/mesos-{{ mesos_version }}.deb" mode=0644
  when: check_mesos_path.stat.exists == False
  register: mesos_archive 
  tags:
    - mesos

- name: mesos install
  sudo: yes
  shell: "dpkg --unpack /tmp/mesos-{{ mesos_version }}.deb && apt-get install -f -y"
  when: mesos_archive|changed
  tags:
    - mesos

- name: config mesos master supervisord
  sudo: yes
  template: src=mesos_master_supervisord.conf.j2 dest=/etc/supervisord/mesos_master.conf
  notify: start mesos master supervisord
  when: mesos_mode == "master"
  tags:
    - mesos

- name: config mesos slave supervisord
  sudo: yes
  template: src=mesos_slave_supervisord.conf.j2 dest=/etc/supervisord/mesos_slave.conf
  notify: start mesos slave supervisord
  when: mesos_mode == "slave"
  tags:
    - mesos

- name: start mesos master supervisord
  sudo: yes
  supervisorctl: 
    name: mesos_master 
    state: present
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
  when: mesos_mode == "master"
  tags:
    - mesos

- name: start mesos slave supervisord
  sudo: yes
  supervisorctl: 
    name: mesos_slave 
    state: present
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
  when: mesos_mode == "slave"
  tags:
    - mesos
