---
- name: restart consul
  sudo: yes
  command: /usr/local/bin/consul-rolling-restart.sh
  notify:
    - wait for consul to listen

- name: restart nginx-consul
  sudo: yes
  command: systemctl restart nginx-consul
