---
- name: ensure customized bin
  sudo: yes
  file:
    path: /opt/bin
    state: directory
  tags:
    - etcd

- name: setup start_etcd script
  sudo: yes
  template:
    src: start_etcd.sh.j2
    dest: /opt/bin/start_etcd.sh
    mode: 0755
  notify: restart etcd
  tags:
    - etcd

- name: setup etcd supervisord config
  sudo: yes
  template:
    src: etcd_supervisord.conf.j2
    dest: "{{ supervisord_conf_dir }}/etcd.conf"
  notify: restart etcd
  tags:
    - etcd

- name: start etcd supervisord
  sudo: yes
  supervisorctl: 
    name: etcd
    state: present
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
  tags:
    - etcd

- include: etcd_browser.yml
