---
- name: create mount point for container volume
  sudo: yes
  file:
    state: directory
    name: "{{ glusterfs_container_data_mount }}"
    recurse: yes
    mode: 0755
  tags:
    - glusterfs

- name: mount container volume
  sudo: yes
  mount:
    state: mounted
    name: "{{ glusterfs_container_data_mount }}"
    fstype: glusterfs
    src: "fs.glusterfs.service.{{ consul_dns_domain }}:/{{ glusterfs_container_data_name }}"
  tags:
    - glusterfs