---
- name: restart haproxy
  sudo: yes
  service: name=haproxy state=restarted

- name: restart marathon
  sudo: yes
  supervisorctl: 
    name: marathon
    state: restarted
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"

- include: consul.yml
