---
- name: copy nginx configuration
  sudo: yes
  template:
    src: mantlui.nginx.j2
    dest: /etc/mantlui.nginx
  tags:
    - mantlui

- name: configure nginx
  sudo: yes
  command: consul-cli kv-write service/nginx/templates/mantlui @/etc/mantlui.nginx
  tags:
    - mantlui

- name: ensure nginx-mantlui docker image is present
  sudo: yes
  command: /usr/bin/docker pull {{ mantlui_nginx_image }}:{{ mantlui_nginx_image_tag }}
  tags:
    - mantlui
    - bootstrap

- name: update mesos ui
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - src: mesos/controllers.js
      dest: /usr/share/mesos/webui/master/static/js
    - src: mesos/services.js
      dest: /usr/share/mesos/webui/master/static/js
    - src: mesos/app.js
      dest: /usr/share/mesos/webui/master/static/js
    - src: mesos/index.html
      dest: /usr/share/mesos/webui/master/static
    - src: mesos/pailer.html
      dest: /usr/share/mesos/webui/master/static
  tags:
    - mantlui

- name: configure nginx-mantlui
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: nginx-mantlui.service.j2
      dest: /usr/lib/systemd/system/nginx-mantlui.service
    - src: nginx-mantlui.env.j2
      dest: /etc/default/nginx-mantlui.env
  notify:
    - reload nginx-mantlui
    - restart nginx-mantlui
  tags:
    - mantlui

- name: enable nginx-mantlui
  sudo: yes
  service:
    name: nginx-mantlui
    enabled: yes
    state: started
  notify:
    - restart nginx-mantlui
  tags:
    - mantlui