---
- name: set ip_forward = 1
  sudo: yes
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present
  ignore_errors: true

- name: change /etc/sysctl.conf
  sudo: yes
  lineinfile: "dest=/etc/sysctl.conf regexp='net.ipv4.ip_forward' line='net.ipv4.ip_forward=1'"
