---
# Setup docker cluster store
- name: update docker default settings
  sudo: yes
  template:
    src: default_docker.j2
    dest: /etc/default/docker
  notify:
    - restart docker
  tags:
    - docker
    - calico

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
    - calico

# Enable calico libnetwork plugin
- name: ensure customized bin
  sudo: yes
  file:
    path: /opt/bin
    state: directory
  tags:
    - calico

- name: copy calicoctl
  sudo: yes
  copy:
    src: calicoctl
    dest: /opt/bin/calicoctl
    mode: 0755
  tags:
    - docker
    - calico

- name: enable calico plugin
  sudo: yes
  shell: "/opt/bin/calicoctl node --libnetwork" 
  tags:
    - docker
    - calico

- name: create calico network
  sudo: yes
  shell: "docker network create -d calico {{ cluster_name }}" 
  tags:
    - docker
    - calico
