---
# Setup etcd proxy
- name: setup start_etcd_proxy script
  sudo: yes
  template:
    src: start_etcd_proxy.sh.j2
    dest: /opt/bin/start_etcd_proxy.sh
    mode: 0755
  notify: restart etcd proxy
  tags:
    - etcd_proxy

- name: setup etcd proxy supervisord config
  sudo: yes
  template:
    src: etcd_proxy_supervisord.conf.j2
    dest: "{{ supervisord_conf_dir }}/etcd_proxy.conf"
  notify: restart etcd proxy
  tags:
    - etcd_proxy

- name: start etcd proxy supervisord
  sudo: yes
  supervisorctl: 
    name: etcd_proxy
    state: present
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
  tags:
    - etcd_proxy

# Enable calico libnetwork plugin
- name: ensure customized bin
  sudo: yes
  file:
    path: /opt/bin
    state: directory
  tags:
    - calico

- name: copy calicoctl
  sudo: yes
  copy:
    src: calicoctl
    dest: /opt/bin/calicoctl
    mode: 0755
  tags:
    - docker
    - calico

- name: enable calico plugin
  sudo: yes
  shell: "/opt/bin/calicoctl node --libnetwork" 
  tags:
    - docker
    - calico

- name: create calico network
  sudo: yes
  shell: "docker network create -d calico {{ cluster_name }}" 
  tags:
    - docker
    - calico
