---
# Ansible modprobe module doesn't provide such functionality
- name: add kernel modules to load at boot time
  sudo: yes
  copy:
    src: calico-modules.conf
    dest: /etc/modules-load.d/calico-modules.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - calico

- name: load kernel module xt_set
  sudo: yes
  modprobe:
    name: xt_set
    state: present
  tags:
    - calico

- name: enable kernel packet forwarding
  sudo: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
  tags:
    - calico

- name: download calicoctl binary
  sudo: yes
  get_url:
    url: "{{ calico_binary }}"
    dest: /usr/bin/calicoctl
    mode: 0755
  tags:
    - calico
    - bootstrap

- name: download calicoctl bash completion script
  sudo: yes
  get_url:
    url: "{{ bintray_baseurl }}/calico/calicoctl.sh"
    dest: /etc/bash_completion.d/calicoctl.sh
    mode: 0644
  tags:
    - calico

# We can't use the Ansible standard docker module as it always starts
# containers after image was pulled
- name: ensure calico docker image is present
  sudo: yes
  command: /usr/bin/docker pull {{ calico_image }}:{{ calico_image_tag }}
  notify:
    - restart calico
  tags:
    - calico
    - bootstrap

- name: set calico environment
  sudo: yes
  copy:
    content: "ETCD_AUTHORITY={{ calico_etcdaddr }}"
    dest: /etc/default/calico
    owner: root
    group: root
    mode: 0644
  notify:
    - restart calico
  tags:
    - calico

- name: generate systemd unit file
  sudo: yes
  template:
    src: calico.service.j2
    dest: /usr/lib/systemd/system/calico.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart calico
  tags:
    - calico

- name: install consul check script
  sudo: yes
  copy:
    src: consul-check-calico-node
    dest: /usr/local/bin
    mode: 0755
  tags:
    - calico

- name: register calico with consul
  sudo: yes
  copy:
    src: calico-service.json
    dest: /etc/consul
  notify:
    - reload consul
  tags:
    - calico

- include: openstack.yml
  when: provider == 'openstack'

- name: enable and start calico
  sudo: yes
  service:
    name: calico
    enabled: yes
    state: started
  tags:
    - calico

- name: ensure mesos-slave directory exists
  sudo: yes
  file:
    path: /etc/mesos-slave/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: check if mesos agent is running
  sudo: yes
  command: systemctl is-active mesos-slave
  register: mesos_agent_active
  failed_when: false
  changed_when: false

- name: configure mesos-slave for networking integration
  sudo: yes
  template:
    src: executor_environment_variables
    dest: /etc/mesos-slave/executor_environment_variables
    mode: 0644
  notify:
    - restart mesos agent
  tags:
    - calico

- meta: flush_handlers

- include: calico-configure.yml
