---
- name: create secret file
  sudo: yes
  when: do_mesos_framework_auth|bool
  copy:
    dest: /etc/chronos/mesos_authentication_secret
    content: "{{ chronos_secret }}"
  notify:
    - restart chronos
  tags:
    - chronos

- name: set principal and secret
  sudo: yes
  when: do_mesos_framework_auth|bool
  copy:
    dest: /etc/chronos/conf/{{ item.key }}
    content: "{{ item.value }}"
  with_items:
    - key: mesos_authentication_principal
      value: "{{ chronos_principal }}"
    - key: mesos_authentication_secret_file
      value: /etc/chronos/mesos_authentication_secret
  notify:
    - restart chronos
  tags:
    - chronos

# remove if option become unset
- name: remove secret file
  sudo: yes
  when: not do_mesos_framework_auth|bool
  file:
    dest: /etc/chronos/mesos_authentication_secret
    state: absent
  notify:
    - restart chronos

- name: remove principal and secret
  sudo: yes
  when: not do_mesos_framework_auth|bool
  file:
    dest: /etc/chronos/conf/{{ item }}
    state: absent
  with_items:
    - mesos_authentication_principal
    - mesos_authentication_secret_file
  notify:
    - restart chronos
  tags:
    - chronos
