---
# Prometheus
supervisord_conf_dir: /etc/supervisord
supervisord_exec_dir: /usr/local/bin
prometheus_image: prom/prometheus
prometheus_image_tag: 0.16.1
cluster_name: mi
host_domain: localhost

# Promdash
promdash_image: prom/promdash
promdash_image_tag: latest
promdash_port: 9091

# Consul exporter
prometheus_consul_exporter_image: prom/consul-exporter
prometheus_consul_exporter_image_tag: latest
consul_hosts: "localhost:8500"
consul_exporter_port: 9107

# Etcd config
etcd_size: 1
etcd_client_port: 2379

# Mesos exporter
prometheus_mesos_exporter_image: prom/mesos-exporter
prometheus_mesos_exporter_image_tag: latest
mesos_hosts: "localhost:5050"
mesos_exporter_port: 9108

# Node exporter
consul_hosts: "localhost:8500"
