---
- name: restart prometheus consul exporter
  sudo: yes
  supervisorctl: 
    name: prometheus_consul_exporter
    state: restarted
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
