---
- name: restart prometheus
  sudo: yes
  supervisorctl: 
    name: prometheus
    state: restarted
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"

- include: alertmanager.yml

- include: consul_exporter.yml

- include: mesos_exporter.yml

- include: promdash.yml

- include: consul.yml
