---

- include_vars: "{{ansible_distribution}}.{{ansible_distribution_release}}.yml"

- include: install.yml

- include: configure.yml

- name: Ensure OpenVPN is started
  sudo: yes
  service: name=openvpn state=started enabled=yes
